version: "3.6"
services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
    - $PWD:/var/www/html
    environment:
      APP_ENV: dev
      APP_SECRET: notASecret
    user: $UID:$GID
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    - 8081:15672